// Aureus Law - Demo Data for Development
// This data is used when Supabase is not connected

import type {
  TeamMember,
  PracticeArea,
  Sector,
  Article,
  ArticleCategory,
  Testimonial,
  FAQ,
  ContactInfo,
  HeroContent,
  Case,
  Task,
  Appointment,
  Client,
  Notification,
  ConsultationRequest,
} from './types'

export const contactInfo: ContactInfo = {
  phone: '+960 300 1000',
  email: 'contact@aureuslaw.mv',
  address: 'Aureus Law, 4th Floor, Champa Building, Boduthakurufaanu Magu, Malé, Maldives 20026',
  hours: 'Sunday - Thursday: 8:00 AM - 5:00 PM'
}

// Firm Statistics
export const firmStats = [
  { label: 'Years of Excellence', value: '15+' },
  { label: 'Cases Resolved', value: '2,500+' },
  { label: 'Corporate Clients', value: '300+' },
  { label: 'Legal Professionals', value: '25+' },
]

// Firm Values
export const firmValues = [
  {
    title: 'Integrity',
    description: 'We uphold the highest ethical standards in every interaction, ensuring transparency and honesty in all our dealings.',
    icon: 'Shield'
  },
  {
    title: 'Excellence',
    description: 'We strive for excellence in legal practice, delivering meticulous work product and innovative solutions to complex challenges.',
    icon: 'Award'
  },
  {
    title: 'Client Focus',
    description: 'Our clients are at the center of everything we do. We listen, understand, and tailor our approach to meet their unique needs.',
    icon: 'Users'
  },
  {
    title: 'Local Expertise',
    description: 'Deep knowledge of Maldivian law and business culture enables us to provide contextually relevant and effective counsel.',
    icon: 'MapPin'
  },
]

export const heroContent: HeroContent = {
  headline: 'Strategic Legal Counsel for the Maldives',
  subheadline: 'Trusted guidance for individuals, businesses, and institutions across every legal challenge.',
  cta_text: 'Book a Consultation',
  cta_link: '/contact/book-consultation'
}

export const practiceAreas: PracticeArea[] = [
  {
    id: '1',
    name: 'Corporate & Commercial Law',
    slug: 'corporate-commercial',
    short_description: 'Strategic legal support for business formation, transactions, and corporate governance.',
    full_description: 'Our corporate and commercial practice provides comprehensive legal support for businesses at every stage of their journey. From entity formation and shareholder agreements to complex M&A transactions, we help clients navigate the legal landscape with confidence.',
    icon_name: 'Building2',
    cover_image_url: null,
    common_needs: ['Company incorporation', 'Shareholder agreements', 'Joint ventures', 'Corporate restructuring', 'Due diligence'],
    related_services: ['Contract Drafting', 'Regulatory Compliance', 'Banking & Finance'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    name: 'Civil Litigation',
    slug: 'civil-litigation',
    short_description: 'Skilled representation in civil disputes and court proceedings.',
    full_description: 'When disputes arise, our litigation team brings strategic thinking and courtroom experience to protect your interests. We handle matters ranging from contract disputes to property claims, always working toward the most favorable resolution.',
    icon_name: 'Scale',
    cover_image_url: null,
    common_needs: ['Contract disputes', 'Property claims', 'Debt recovery', 'Injunctions', 'Appeals'],
    related_services: ['Dispute Resolution', 'Debt Recovery'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '3',
    name: 'Criminal Defense',
    slug: 'criminal-defense',
    short_description: 'Vigorous defense of your rights in criminal matters.',
    full_description: 'Every person deserves a strong defense. Our criminal defense team provides confidential, dedicated representation for individuals facing charges, ensuring your rights are protected throughout the legal process.',
    icon_name: 'Shield',
    cover_image_url: null,
    common_needs: ['Investigation stage support', 'Court representation', 'Bail applications', 'Appeals', 'Record expungement'],
    related_services: ['White Collar Investigations'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '4',
    name: 'Family Law',
    slug: 'family-law',
    short_description: 'Compassionate guidance through sensitive family matters.',
    full_description: 'Family matters require both legal expertise and emotional sensitivity. We guide clients through divorce, custody, and inheritance issues with discretion and care, always prioritizing the well-being of families.',
    icon_name: 'Heart',
    cover_image_url: null,
    common_needs: ['Divorce proceedings', 'Child custody', 'Maintenance claims', 'Prenuptial agreements', 'Adoption'],
    related_services: ['Inheritance & Estates'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '5',
    name: 'Employment & Labour',
    slug: 'employment-labour',
    short_description: 'Protecting rights in the workplace for employers and employees.',
    full_description: 'Whether you are an employer establishing workplace policies or an employee facing unfair treatment, our employment practice provides balanced, practical legal guidance aligned with Maldivian labor law.',
    icon_name: 'Users',
    cover_image_url: null,
    common_needs: ['Employment contracts', 'Wrongful termination', 'Workplace policies', 'Discrimination claims', 'Severance negotiations'],
    related_services: ['Regulatory Compliance', 'Civil Litigation'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: false,
    is_visible: true,
    sort_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '6',
    name: 'Property & Land Matters',
    slug: 'property-land',
    short_description: 'Expert guidance on property transactions and land disputes.',
    full_description: 'Property matters in the Maldives involve unique considerations. We assist with purchases, leases, development agreements, and dispute resolution, ensuring your property interests are secure.',
    icon_name: 'Home',
    cover_image_url: null,
    common_needs: ['Property purchases', 'Land registration', 'Lease agreements', 'Title disputes', 'Development contracts'],
    related_services: ['Construction Law', 'Civil Litigation'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 6,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '7',
    name: 'Banking & Finance',
    slug: 'banking-finance',
    short_description: 'Legal support for financial transactions and institutions.',
    full_description: 'From loan documentation to regulatory compliance, we support banks, financial institutions, and borrowers through complex financial transactions and regulatory matters.',
    icon_name: 'Landmark',
    cover_image_url: null,
    common_needs: ['Loan documentation', 'Security arrangements', 'Financial regulations', 'Banking disputes', 'Islamic finance'],
    related_services: ['Corporate Law', 'Regulatory Compliance'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: false,
    is_visible: true,
    sort_order: 7,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '8',
    name: 'Dispute Resolution & Arbitration',
    slug: 'dispute-resolution',
    short_description: 'Alternative pathways to resolve conflicts efficiently.',
    full_description: 'Not every dispute needs to go to court. We offer mediation and arbitration services that can resolve conflicts faster and more cost-effectively while maintaining confidentiality.',
    icon_name: 'MessageSquare',
    cover_image_url: null,
    common_needs: ['Commercial arbitration', 'Mediation services', 'Negotiated settlements', 'International disputes', 'Enforcement of awards'],
    related_services: ['Civil Litigation', 'Corporate Law'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: false,
    is_visible: true,
    sort_order: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  }
]

export const sectors: Sector[] = [
  {
    id: '1',
    name: 'Hospitality & Resorts',
    slug: 'hospitality-resorts',
    short_description: 'Legal partner to the Maldives\' world-renowned hospitality industry.',
    full_description: 'The hospitality sector is the cornerstone of the Maldivian economy. We provide comprehensive legal support to resorts, hotels, and tourism operators, from development agreements to employment matters and regulatory compliance.',
    icon_name: 'Building',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    name: 'Construction & Real Estate',
    slug: 'construction-real-estate',
    short_description: 'Building the legal foundation for development projects.',
    full_description: 'We support developers, contractors, and property owners through all phases of construction and real estate projects, from land acquisition to dispute resolution.',
    icon_name: 'HardHat',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '3',
    name: 'SMEs & Local Businesses',
    slug: 'smes-local-businesses',
    short_description: 'Empowering Maldivian entrepreneurs and growing businesses.',
    full_description: 'Small and medium enterprises are the backbone of the local economy. We provide practical, affordable legal support tailored to the needs of growing Maldivian businesses.',
    icon_name: 'Store',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '4',
    name: 'Financial Services',
    slug: 'financial-services',
    short_description: 'Navigating the regulated financial landscape.',
    full_description: 'From banks to insurance companies to fintech startups, we help financial services clients manage regulatory requirements while pursuing growth opportunities.',
    icon_name: 'TrendingUp',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: false,
    is_visible: true,
    sort_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '5',
    name: 'International Clients',
    slug: 'international-clients',
    short_description: 'Your gateway to legal certainty in the Maldives.',
    full_description: 'Foreign investors and international businesses need local expertise. We bridge the gap, providing clear guidance on Maldivian law and facilitating smooth cross-border transactions.',
    icon_name: 'Globe',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  }
]

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    profile_id: null,
    full_name: 'Ahmed Rasheed',
    slug: 'ahmed-rasheed',
    role_title: 'Managing Partner',
    email: 'ahmed.rasheed@aureuslaw.mv',
    phone: '+960 300 1001',
    bio: 'Ahmed Rasheed is the founding and managing partner of Aureus Law. With over 20 years of experience in Maldivian law, he has advised multinational corporations, government bodies, and high-net-worth individuals on complex legal matters. Ahmed is recognized as one of the leading corporate lawyers in the Maldives.',
    education: ['LLM, University of London', 'LLB (Hons), Maldives National University'],
    admissions: ['Supreme Court of Maldives', 'High Court of Maldives'],
    languages: ['Dhivehi', 'English', 'Arabic'],
    years_experience: 20,
    photo_url: null,
    is_partner: true,
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    profile_id: null,
    full_name: 'Fathimath Latheefa',
    slug: 'fathimath-latheefa',
    role_title: 'Senior Partner',
    email: 'fathimath.latheefa@aureuslaw.mv',
    phone: '+960 300 1002',
    bio: 'Fathimath Latheefa heads the firm\'s litigation and dispute resolution practice. She has represented clients in landmark cases before the Supreme Court and has extensive experience in commercial disputes, arbitration, and family law matters. Fathimath is known for her strategic approach and courtroom presence.',
    education: ['LLM, University of Melbourne', 'LLB, Villa College'],
    admissions: ['Supreme Court of Maldives', 'High Court of Maldives'],
    languages: ['Dhivehi', 'English'],
    years_experience: 15,
    photo_url: null,
    is_partner: true,
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '3',
    profile_id: null,
    full_name: 'Hassan Waheed',
    slug: 'hassan-waheed',
    role_title: 'Partner',
    email: 'hassan.waheed@aureuslaw.mv',
    phone: '+960 300 1003',
    bio: 'Hassan Waheed specializes in property law, banking and finance, and corporate transactions. He has advised on some of the largest resort development projects in the Maldives and regularly assists financial institutions with lending and security documentation.',
    education: ['LLB (Hons), Brunel University London', 'Diploma in Islamic Banking'],
    admissions: ['Supreme Court of Maldives', 'High Court of Maldives'],
    languages: ['Dhivehi', 'English'],
    years_experience: 12,
    photo_url: null,
    is_partner: true,
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '4',
    profile_id: null,
    full_name: 'Aishath Nahula',
    slug: 'aishath-nahula',
    role_title: 'Partner',
    email: 'aishath.nahula@aureuslaw.mv',
    phone: '+960 300 1004',
    bio: 'Aishath Nahula leads the employment and regulatory practice at Aureus Law. She advises both employers and employees on workplace matters and has developed compliance frameworks for numerous organizations in the hospitality and financial services sectors.',
    education: ['LLM, National University of Singapore', 'LLB, Maldives National University'],
    admissions: ['High Court of Maldives', 'Civil Court of Maldives'],
    languages: ['Dhivehi', 'English', 'Hindi'],
    years_experience: 10,
    photo_url: null,
    is_partner: true,
    is_featured: false,
    is_visible: true,
    sort_order: 4,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '5',
    profile_id: null,
    full_name: 'Mohamed Shareef',
    slug: 'mohamed-shareef',
    role_title: 'Senior Associate',
    email: 'mohamed.shareef@aureuslaw.mv',
    phone: '+960 300 1005',
    bio: 'Mohamed Shareef focuses on corporate and commercial law, assisting clients with business formations, contracts, and regulatory matters. He has particular expertise in the hospitality sector and regularly advises resort operators on operational legal matters.',
    education: ['LLB (Hons), University of Wolverhampton', 'Certificate in International Arbitration'],
    admissions: ['High Court of Maldives', 'Civil Court of Maldives'],
    languages: ['Dhivehi', 'English'],
    years_experience: 7,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 5,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '6',
    profile_id: null,
    full_name: 'Aminath Shifana',
    slug: 'aminath-shifana',
    role_title: 'Senior Associate',
    email: 'aminath.shifana@aureuslaw.mv',
    phone: '+960 300 1006',
    bio: 'Aminath Shifana practices in the areas of civil litigation and family law. She is known for her compassionate approach to sensitive family matters and her thorough preparation in court proceedings. Aminath has successfully handled numerous custody and divorce cases.',
    education: ['LLB, Maldives National University', 'Certificate in Mediation'],
    admissions: ['High Court of Maldives', 'Civil Court of Maldives', 'Family Court'],
    languages: ['Dhivehi', 'English'],
    years_experience: 6,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 6,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '7',
    profile_id: null,
    full_name: 'Ibrahim Nazim',
    slug: 'ibrahim-nazim',
    role_title: 'Associate',
    email: 'ibrahim.nazim@aureuslaw.mv',
    phone: '+960 300 1007',
    bio: 'Ibrahim Nazim works across the firm\'s practice areas with a focus on property law and contract drafting. He assists clients with property transactions, lease agreements, and commercial contracts, bringing meticulous attention to detail to every matter.',
    education: ['LLB, Villa College'],
    admissions: ['Civil Court of Maldives', 'Magistrate Courts'],
    languages: ['Dhivehi', 'English'],
    years_experience: 4,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 7,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '8',
    profile_id: null,
    full_name: 'Mariyam Shifa',
    slug: 'mariyam-shifa',
    role_title: 'Associate',
    email: 'mariyam.shifa@aureuslaw.mv',
    phone: '+960 300 1008',
    bio: 'Mariyam Shifa specializes in immigration law and administrative matters. She assists both individuals and businesses with visa applications, work permits, and dealings with government authorities. Her practical approach helps clients navigate bureaucratic processes efficiently.',
    education: ['LLB (Hons), University of London International', 'Diploma in Administrative Law'],
    admissions: ['Civil Court of Maldives'],
    languages: ['Dhivehi', 'English', 'Sinhala'],
    years_experience: 3,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 8,
    linkedin_url: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  }
]

export const articleCategories: ArticleCategory[] = [
  { id: '1', name: 'Legal Updates', slug: 'legal-updates', description: 'Recent changes in Maldivian law and regulations', sort_order: 1, created_at: '2024-01-01' },
  { id: '2', name: 'Business Insights', slug: 'business-insights', description: 'Practical guidance for businesses operating in the Maldives', sort_order: 2, created_at: '2024-01-01' },
  { id: '3', name: 'Industry Focus', slug: 'industry-focus', description: 'Deep dives into sector-specific legal matters', sort_order: 3, created_at: '2024-01-01' },
  { id: '4', name: 'Client Guides', slug: 'client-guides', description: 'Helpful resources for common legal questions', sort_order: 4, created_at: '2024-01-01' },
  { id: '5', name: 'Firm News', slug: 'firm-news', description: 'Updates and announcements from Aureus Law', sort_order: 5, created_at: '2024-01-01' }
]

export const articles: Article[] = [
  {
    id: '1',
    title: 'Understanding Employment Law Changes in 2024',
    slug: 'employment-law-changes-2024',
    excerpt: 'Recent amendments to the Employment Act bring significant changes for employers and employees. Here is what you need to know.',
    content: '<p>The Maldivian Employment Act has undergone several important amendments that affect both employers and employees operating in the country. These changes aim to modernize workplace regulations and provide greater protections for workers while maintaining flexibility for businesses.</p><h2>Key Changes for Employers</h2><p>Employers must now provide written employment contracts within 14 days of employment commencement. The contracts must include specific terms regarding leave entitlements, notice periods, and disciplinary procedures.</p><h2>Enhanced Leave Provisions</h2><p>Annual leave entitlements have been clarified, with employees now entitled to a minimum of 30 days paid leave after one year of service. Sick leave provisions have also been strengthened.</p><h2>What This Means for Your Business</h2><p>We recommend all employers review their current employment contracts and HR policies to ensure compliance with the new requirements. Our employment team is available to assist with policy reviews and contract updates.</p>',
    cover_image_url: null,
    category_id: '1',
    author_id: '4',
    status: 'published',
    is_featured: true,
    read_time_minutes: 5,
    tags: ['employment law', 'HR', 'compliance'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2024-03-01',
    created_at: '2024-03-01',
    updated_at: '2024-03-01',
    category: articleCategories[0],
    author: teamMembers[3]
  },
  {
    id: '2',
    title: 'Guide to Property Purchases in the Maldives',
    slug: 'property-purchases-guide-maldives',
    excerpt: 'A comprehensive guide to buying property in the Maldives, including foreign ownership rules and due diligence requirements.',
    content: '<p>Property ownership in the Maldives involves unique considerations that both local and foreign buyers must understand. This guide covers the essential legal aspects of property transactions in our jurisdiction.</p><h2>Foreign Ownership Rules</h2><p>Foreign nationals and companies can own property in the Maldives under specific conditions, primarily through long-term lease arrangements rather than freehold ownership. Understanding these distinctions is crucial for international investors.</p><h2>Due Diligence Requirements</h2><p>Before completing any property transaction, thorough due diligence is essential. This includes title searches, verification of ownership rights, review of any encumbrances, and confirmation of necessary permits.</p><h2>The Transaction Process</h2><p>Property transactions typically involve negotiation, preliminary agreements, due diligence, final documentation, and registration. Each stage requires careful attention to legal requirements.</p><p>Contact our property team for personalized guidance on your property transaction.</p>',
    cover_image_url: null,
    category_id: '4',
    author_id: '3',
    status: 'published',
    is_featured: true,
    read_time_minutes: 7,
    tags: ['property law', 'real estate', 'foreign investment'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2024-02-15',
    created_at: '2024-02-15',
    updated_at: '2024-02-15',
    category: articleCategories[3],
    author: teamMembers[2]
  },
  {
    id: '3',
    title: 'Corporate Governance Best Practices for Maldivian Companies',
    slug: 'corporate-governance-best-practices',
    excerpt: 'Strong corporate governance builds investor confidence and regulatory compliance. Learn the essentials for Maldivian businesses.',
    content: '<p>Good corporate governance is the foundation of sustainable business success. For companies operating in the Maldives, implementing robust governance practices is not just about compliance—it is about building trust with investors, partners, and regulators.</p><h2>Board Structure and Composition</h2><p>An effective board should include a mix of executive and non-executive directors with diverse skills and experience. Clear delineation of roles between the board and management is essential.</p><h2>Shareholder Rights</h2><p>Protecting shareholder rights through proper meeting procedures, voting mechanisms, and information disclosure builds confidence among investors and facilitates capital raising.</p><h2>Compliance and Risk Management</h2><p>Establishing clear compliance frameworks and risk management processes helps companies identify and address potential issues before they become problems.</p><p>Our corporate team can assist with governance reviews and implementation of best practices.</p>',
    cover_image_url: null,
    category_id: '2',
    author_id: '1',
    status: 'published',
    is_featured: false,
    read_time_minutes: 6,
    tags: ['corporate law', 'governance', 'compliance'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2024-02-01',
    created_at: '2024-02-01',
    updated_at: '2024-02-01',
    category: articleCategories[1],
    author: teamMembers[0]
  },
  {
    id: '4',
    title: 'Navigating Resort Development Agreements in the Maldives',
    slug: 'resort-development-agreements',
    excerpt: 'Key considerations for investors and developers entering the Maldivian hospitality sector.',
    content: '<p>The Maldives tourism industry continues to attract significant investment. Understanding the legal framework for resort development is essential for successful projects.</p><h2>Lease Arrangements</h2><p>Resort islands are typically leased from the government for periods of up to 50 years. The terms and conditions of these leases significantly impact project viability.</p><h2>Development Requirements</h2><p>Strict environmental and development requirements apply to resort projects. Early engagement with regulatory requirements helps avoid costly delays.</p>',
    cover_image_url: null,
    category_id: '3',
    author_id: '3',
    status: 'published',
    is_featured: false,
    read_time_minutes: 8,
    tags: ['hospitality', 'development', 'investment'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2024-01-20',
    created_at: '2024-01-20',
    updated_at: '2024-01-20',
    category: articleCategories[2],
    author: teamMembers[2]
  }
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    client_name: 'Ibrahim Moosa',
    client_title: 'CEO',
    company_name: 'Island Resorts Group',
    content: 'Aureus Law has been our trusted legal partner for over five years. Their understanding of the hospitality industry and proactive approach to legal matters has been invaluable to our expansion across the Maldives.',
    rating: 5,
    practice_area_id: '1',
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2024-01-01'
  },
  {
    id: '2',
    client_name: 'Sarah Chen',
    client_title: 'Regional Director',
    company_name: 'Pacific Investments Ltd',
    content: 'When we decided to invest in the Maldives, Aureus Law provided clear, practical guidance that made the process smooth. Their team understood our commercial objectives and delivered results.',
    rating: 5,
    practice_area_id: '1',
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2024-01-01'
  },
  {
    id: '3',
    client_name: 'Ahmed Saleem',
    client_title: 'Managing Director',
    company_name: 'Coral Construction',
    content: 'The property and construction team at Aureus Law helped us navigate complex development agreements and resolve a challenging dispute. Professional, thorough, and always available when needed.',
    rating: 5,
    practice_area_id: '6',
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2024-01-01'
  }
]

export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'How do I schedule a consultation with Aureus Law?',
    answer: 'You can schedule a consultation by filling out our online booking form, calling our office at +960 300 1000, or sending an email to contact@aureuslaw.mv. We typically respond within one business day and will arrange a time that suits your schedule.',
    category: 'General',
    practice_area_id: null,
    sort_order: 1,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    question: 'What are your fees and billing practices?',
    answer: 'Our fees vary depending on the nature and complexity of the matter. We offer fixed-fee arrangements for routine matters and hourly billing for more complex work. During your initial consultation, we will provide a clear estimate of costs and explain our billing practices.',
    category: 'General',
    practice_area_id: null,
    sort_order: 2,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '3',
    question: 'Do you offer services in languages other than English and Dhivehi?',
    answer: 'Yes, several of our lawyers are fluent in additional languages including Arabic, Hindi, and Sinhala. Please let us know your language preference when scheduling your consultation.',
    category: 'General',
    practice_area_id: null,
    sort_order: 3,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '4',
    question: 'How do I incorporate a company in the Maldives?',
    answer: 'Company incorporation involves registering with the Ministry of Economic Development, obtaining necessary licenses, and preparing constitutional documents. Our corporate team can guide you through the entire process, from choosing the right business structure to completing registration.',
    category: 'Business',
    practice_area_id: '1',
    sort_order: 4,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '5',
    question: 'What should I do if I receive a legal notice?',
    answer: 'Do not ignore any legal notice. Contact a lawyer promptly to understand your rights and obligations. Time limits often apply to legal responses, so early advice is essential.',
    category: 'Disputes',
    practice_area_id: '2',
    sort_order: 5,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '6',
    question: 'How long does a typical court case take in the Maldives?',
    answer: 'Case duration varies significantly depending on the court, complexity, and nature of the dispute. Simple matters may resolve in months, while complex litigation can take several years. We can provide more specific guidance based on your circumstances.',
    category: 'Disputes',
    practice_area_id: '2',
    sort_order: 6,
    is_visible: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  }
]

// Portal Demo Data
export const demoClients: Client[] = [
  {
    id: '1',
    name: 'Island Resorts Group',
    client_type: 'business',
    email: 'legal@islandresorts.mv',
    phone: '+960 400 1000',
    address: 'Tower 1, Hulhumalé Business Park',
    company_name: 'Island Resorts Group Pvt Ltd',
    contact_person: 'Ibrahim Moosa',
    notes: 'Major hospitality client. VIP treatment.',
    is_active: true,
    created_by: null,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    name: 'Mohamed Rashid',
    client_type: 'individual',
    email: 'mrashid@gmail.com',
    phone: '+960 777 1234',
    address: 'H. Sunrise, Malé',
    company_name: null,
    contact_person: null,
    notes: 'Family law matter - divorce proceedings.',
    is_active: true,
    created_by: null,
    created_at: '2024-01-15',
    updated_at: '2024-01-15'
  },
  {
    id: '3',
    name: 'Coral Construction Pvt Ltd',
    client_type: 'business',
    email: 'info@coralconstruction.mv',
    phone: '+960 400 2000',
    address: 'Industrial Zone, Thilafushi',
    company_name: 'Coral Construction Pvt Ltd',
    contact_person: 'Ahmed Saleem',
    notes: 'Construction and development client.',
    is_active: true,
    created_by: null,
    created_at: '2024-02-01',
    updated_at: '2024-02-01'
  }
]

export const demoCases: Case[] = [
  {
    id: '1',
    case_number: 'AL-2024-00001',
    title: 'Island Resorts Group - Employment Dispute',
    description: 'Wrongful termination claim by former employee. Client is defendant.',
    client_id: '1',
    practice_area_id: '5',
    status: 'active',
    priority: 'high',
    court_name: 'Employment Tribunal',
    court_case_number: 'ET-2024-0123',
    next_hearing_date: '2024-04-15T10:00:00Z',
    deadline: '2024-04-10T17:00:00Z',
    notes: 'Key witness interview scheduled for next week.',
    created_by: null,
    created_at: '2024-02-01',
    updated_at: '2024-03-01'
  },
  {
    id: '2',
    case_number: 'AL-2024-00002',
    title: 'Rashid Divorce Proceedings',
    description: 'Contested divorce with child custody dispute.',
    client_id: '2',
    practice_area_id: '4',
    status: 'active',
    priority: 'medium',
    court_name: 'Family Court',
    court_case_number: 'FC-2024-0456',
    next_hearing_date: '2024-04-20T09:00:00Z',
    deadline: null,
    notes: 'Mediation attempt scheduled before hearing.',
    created_by: null,
    created_at: '2024-01-20',
    updated_at: '2024-03-05'
  },
  {
    id: '3',
    case_number: 'AL-2024-00003',
    title: 'Coral Construction - Contract Review',
    description: 'Review and negotiation of major development contract for new resort project.',
    client_id: '3',
    practice_area_id: '1',
    status: 'active',
    priority: 'high',
    court_name: null,
    court_case_number: null,
    next_hearing_date: null,
    deadline: '2024-03-30T17:00:00Z',
    notes: 'Client meeting next week to discuss revised terms.',
    created_by: null,
    created_at: '2024-03-01',
    updated_at: '2024-03-10'
  },
  {
    id: '4',
    case_number: 'AL-2024-00004',
    title: 'Property Dispute - Land Registration',
    description: 'Title dispute over commercial property in Hulhumalé.',
    client_id: '1',
    practice_area_id: '6',
    status: 'pending',
    priority: 'medium',
    court_name: 'Civil Court',
    court_case_number: null,
    next_hearing_date: null,
    deadline: null,
    notes: 'Awaiting response from opposing party.',
    created_by: null,
    created_at: '2024-02-15',
    updated_at: '2024-02-28'
  }
]

export const demoTasks: Task[] = [
  {
    id: '1',
    title: 'Prepare witness statements',
    description: 'Draft witness statements for employment tribunal hearing.',
    case_id: '1',
    assigned_to: null,
    assigned_by: null,
    priority: 'high',
    status: 'in_progress',
    due_date: '2024-04-08T17:00:00Z',
    completed_at: null,
    created_at: '2024-03-01',
    updated_at: '2024-03-10'
  },
  {
    id: '2',
    title: 'Review contract draft',
    description: 'Review latest draft of development contract and prepare markup.',
    case_id: '3',
    assigned_to: null,
    assigned_by: null,
    priority: 'high',
    status: 'pending',
    due_date: '2024-03-25T17:00:00Z',
    completed_at: null,
    created_at: '2024-03-10',
    updated_at: '2024-03-10'
  },
  {
    id: '3',
    title: 'File mediation request',
    description: 'Submit mediation request to Family Court for Rashid matter.',
    case_id: '2',
    assigned_to: null,
    assigned_by: null,
    priority: 'medium',
    status: 'completed',
    due_date: '2024-03-15T17:00:00Z',
    completed_at: '2024-03-14T14:30:00Z',
    created_at: '2024-03-01',
    updated_at: '2024-03-14'
  },
  {
    id: '4',
    title: 'Client meeting preparation',
    description: 'Prepare agenda and documents for Coral Construction meeting.',
    case_id: '3',
    assigned_to: null,
    assigned_by: null,
    priority: 'medium',
    status: 'pending',
    due_date: '2024-03-22T12:00:00Z',
    completed_at: null,
    created_at: '2024-03-15',
    updated_at: '2024-03-15'
  }
]

export const demoAppointments: Appointment[] = [
  {
    id: '1',
    title: 'Island Resorts Group - Case Strategy Meeting',
    description: 'Discuss strategy for upcoming tribunal hearing.',
    client_id: '1',
    case_id: '1',
    consultation_request_id: null,
    assigned_to: null,
    location: 'Aureus Law Office',
    start_time: '2024-03-20T10:00:00Z',
    end_time: '2024-03-20T11:30:00Z',
    status: 'confirmed',
    notes: 'Ibrahim Moosa and HR Director attending.',
    created_by: null,
    created_at: '2024-03-10',
    updated_at: '2024-03-10'
  },
  {
    id: '2',
    title: 'Coral Construction - Contract Negotiation',
    description: 'Review revised contract terms with client.',
    client_id: '3',
    case_id: '3',
    consultation_request_id: null,
    assigned_to: null,
    location: 'Client Office',
    start_time: '2024-03-25T14:00:00Z',
    end_time: '2024-03-25T16:00:00Z',
    status: 'pending',
    notes: 'Bring printed copies of contract comparison.',
    created_by: null,
    created_at: '2024-03-15',
    updated_at: '2024-03-15'
  },
  {
    id: '3',
    title: 'New Consultation - Business Formation',
    description: 'Initial consultation for new business client.',
    client_id: null,
    case_id: null,
    consultation_request_id: null,
    assigned_to: null,
    location: 'Virtual Meeting',
    start_time: '2024-03-21T09:00:00Z',
    end_time: '2024-03-21T10:00:00Z',
    status: 'confirmed',
    notes: 'Prospective client from Dubai interested in resort investment.',
    created_by: null,
    created_at: '2024-03-18',
    updated_at: '2024-03-18'
  }
]

export const demoNotifications: Notification[] = [
  {
    id: '1',
    profile_id: '',
    title: 'New task assigned',
    message: 'You have been assigned to review contract draft for Coral Construction.',
    type: 'task',
    link: '/portal/tasks',
    is_read: false,
    created_at: '2024-03-15T09:00:00Z'
  },
  {
    id: '2',
    profile_id: '',
    title: 'Hearing reminder',
    message: 'Employment Tribunal hearing for Island Resorts Group in 3 days.',
    type: 'reminder',
    link: '/portal/cases/1',
    is_read: false,
    created_at: '2024-03-12T08:00:00Z'
  },
  {
    id: '3',
    profile_id: '',
    title: 'Document uploaded',
    message: 'New document uploaded to Rashid Divorce Proceedings case.',
    type: 'document',
    link: '/portal/cases/2',
    is_read: true,
    created_at: '2024-03-10T14:30:00Z'
  }
]

export const demoConsultationRequests: ConsultationRequest[] = [
  {
    id: '1',
    full_name: 'Ali Hassan',
    email: 'ali.hassan@example.com',
    phone: '+960 777 5555',
    client_type: 'individual',
    company_name: null,
    practice_area_id: '4',
    preferred_date: '2024-03-25',
    preferred_time: 'morning',
    message: 'I need advice regarding a family matter involving child custody.',
    status: 'new',
    internal_notes: null,
    assigned_to: null,
    created_at: '2024-03-18T10:00:00Z',
    updated_at: '2024-03-18T10:00:00Z'
  },
  {
    id: '2',
    full_name: 'Fatima Ahmed',
    email: 'fatima@oceanventures.mv',
    phone: '+960 400 8888',
    client_type: 'business',
    company_name: 'Ocean Ventures Pvt Ltd',
    practice_area_id: '1',
    preferred_date: '2024-03-27',
    preferred_time: 'afternoon',
    message: 'Looking for legal support for a new joint venture agreement.',
    status: 'reviewed',
    internal_notes: 'Potential high-value client. Hassan to follow up.',
    assigned_to: null,
    created_at: '2024-03-16T14:00:00Z',
    updated_at: '2024-03-17T09:00:00Z'
  }
]

// Job Openings
export const jobOpenings = [
  {
    id: '1',
    title: 'Associate Attorney - Corporate Law',
    type: 'Full-time',
    location: 'Male, Maldives',
    description: 'We are seeking a motivated Associate Attorney to join our Corporate & Commercial Law practice. The ideal candidate will assist senior partners in handling complex corporate transactions, M&A deals, and joint venture agreements.',
    requirements: [
      'LLB from a recognized university',
      '2-4 years of experience in corporate law',
      'Strong drafting and negotiation skills',
      'Fluency in English and Dhivehi',
      'Excellent attention to detail'
    ],
    posted_date: '2024-03-01',
  },
  {
    id: '2',
    title: 'Legal Associate - Litigation',
    type: 'Full-time',
    location: 'Male, Maldives',
    description: 'Join our Litigation team to represent clients in civil and commercial disputes before Maldivian courts. You will work on case preparation, legal research, and court appearances.',
    requirements: [
      'LLB from a recognized university',
      '1-3 years of litigation experience',
      'Strong advocacy and research skills',
      'Admission to practice in Maldives',
      'Ability to work under pressure'
    ],
    posted_date: '2024-03-10',
  },
  {
    id: '3',
    title: 'Paralegal',
    type: 'Full-time',
    location: 'Male, Maldives',
    description: 'Support our legal team with document preparation, research, and administrative tasks. An excellent opportunity for those looking to build a career in law.',
    requirements: [
      'Degree in Law or related field',
      'Strong organizational skills',
      'Proficiency in Microsoft Office',
      'Fluency in English and Dhivehi',
      'Attention to detail'
    ],
    posted_date: '2024-03-15',
  }
]

// Alias exports for portal compatibility
export const matters = demoCases.map((c, idx) => ({
  ...c,
  title: c.title,
  matter_number: c.case_number,
  assigned_lawyers: idx < 2 ? ['lawyer-1', 'lawyer-2'] : ['lawyer-1'],
  lead_lawyer_id: 'lawyer-1',
  priority: c.priority || 'medium',
}))

export const clients = demoClients

export const timeEntries = [
  {
    id: 'te-1',
    lawyer_id: 'lawyer-1',
    matter_id: 'case-1',
    date: '2024-03-18',
    hours: 2.5,
    description: 'Contract review and markup',
    billable: true,
    rate: 350,
  },
  {
    id: 'te-2',
    lawyer_id: 'lawyer-1',
    matter_id: 'case-2',
    date: '2024-03-18',
    hours: 1.5,
    description: 'Client meeting - due diligence discussion',
    billable: true,
    rate: 350,
  },
  {
    id: 'te-3',
    lawyer_id: 'lawyer-1',
    matter_id: 'case-3',
    date: '2024-03-18',
    hours: 3.0,
    description: 'Court filing preparation',
    billable: true,
    rate: 350,
  },
  {
    id: 'te-4',
    lawyer_id: 'lawyer-2',
    matter_id: 'case-1',
    date: '2024-03-18',
    hours: 2.0,
    description: 'Legal research on regulatory requirements',
    billable: true,
    rate: 300,
  },
  {
    id: 'te-5',
    lawyer_id: 'lawyer-1',
    matter_id: 'case-4',
    date: '2024-03-17',
    hours: 4.0,
    description: 'Property deed review and verification',
    billable: true,
    rate: 350,
  },
]
