// Aureus Law - Demo Data for Development
// This data is used when Supabase is not connected

import type {
  TeamMember,
  PracticeArea,
  Sector,
  Article,
  ArticleCategory,
  Testimonial,
  FAQ,
  ContactInfo,
  HeroContent,
  Case,
  Task,
  Appointment,
  Client,
  Notification,
  ConsultationRequest,
} from './types'

export const contactInfo: ContactInfo = {
  phone: '+960 300 1000',
  email: 'contact@aureuslaw.mv',
  address: 'Aureus Law, 4th Floor, Champa Building, Boduthakurufaanu Magu, Malé, Maldives 20026',
  hours: 'Sunday - Thursday: 8:00 AM - 5:00 PM'
}

// Firm Statistics
export const firmStats = [
  { label: 'Years of Excellence', value: '15+' },
  { label: 'Cases Resolved', value: '2,500+' },
  { label: 'Corporate Clients', value: '300+' },
  { label: 'Legal Professionals', value: '25+' },
]

// Firm Values
export const firmValues = [
  {
    title: 'Integrity',
    description: 'We uphold honesty, professionalism, confidentiality, and ethical legal practice in every matter we handle.',
    icon: 'Shield'
  },
  {
    title: 'Client Commitment',
    description: 'We prioritize responsiveness, transparency, and practical legal guidance tailored to each client\'s needs.',
    icon: 'Users'
  },
  {
    title: 'Excellence & Precision',
    description: 'We approach every matter with diligence, attention to detail, and a commitment to delivering high-quality legal work.',
    icon: 'Award'
  },
  {
    title: 'Accountability',
    description: 'We believe in clear communication, responsible practice, and maintaining trust through consistent professional standards.',
    icon: 'MapPin'
  },
]

export const heroContent: HeroContent = {
  headline: 'Independent Counsel Driven by Justice',
  subheadline: 'Principled, practical, and client-focused legal services for individuals, businesses, and institutions across the Maldives.',
  cta_text: 'Book a Consultation',
  cta_link: '/contact/book-consultation'
}

export const practiceAreas: PracticeArea[] = [
  {
    id: '1',
    name: 'Corporate & Commercial Law',
    slug: 'corporate-commercial',
    short_description: 'Strategic legal support for business formation, transactions, and corporate governance.',
    full_description: 'Our corporate and commercial practice provides comprehensive legal support for businesses at every stage of their journey. From entity formation and shareholder agreements to complex M&A transactions, we help clients navigate the legal landscape with confidence.',
    icon_name: 'Building2',
    cover_image_url: null,
    common_needs: ['Company incorporation', 'Shareholder agreements', 'Joint ventures', 'Corporate restructuring', 'Due diligence'],
    related_services: ['Contract Drafting', 'Regulatory Compliance', 'Banking & Finance'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '2',
    name: 'Civil Litigation',
    slug: 'civil-litigation',
    short_description: 'Skilled representation in civil disputes and court proceedings.',
    full_description: 'When disputes arise, our litigation team brings strategic thinking and courtroom experience to protect your interests. We handle matters ranging from contract disputes to property claims, always working toward the most favorable resolution.',
    icon_name: 'Scale',
    cover_image_url: null,
    common_needs: ['Contract disputes', 'Property claims', 'Debt recovery', 'Injunctions', 'Appeals'],
    related_services: ['Dispute Resolution', 'Debt Recovery'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '3',
    name: 'Criminal Defense',
    slug: 'criminal-defense',
    short_description: 'Vigorous defense of your rights in criminal matters.',
    full_description: 'Every person deserves a strong defense. Our criminal defense team provides confidential, dedicated representation for individuals facing charges, ensuring your rights are protected throughout the legal process.',
    icon_name: 'Shield',
    cover_image_url: null,
    common_needs: ['Investigation stage support', 'Court representation', 'Bail applications', 'Appeals', 'Record expungement'],
    related_services: ['White Collar Investigations'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '4',
    name: 'Family Law',
    slug: 'family-law',
    short_description: 'Compassionate guidance through sensitive family matters.',
    full_description: 'Family matters require both legal expertise and emotional sensitivity. We guide clients through divorce, custody, and inheritance issues with discretion and care, always prioritizing the well-being of families.',
    icon_name: 'Heart',
    cover_image_url: null,
    common_needs: ['Divorce proceedings', 'Child custody', 'Maintenance claims', 'Prenuptial agreements', 'Adoption'],
    related_services: ['Inheritance & Estates'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 4,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '5',
    name: 'Employment & Labour',
    slug: 'employment-labour',
    short_description: 'Protecting rights in the workplace for employers and employees.',
    full_description: 'Whether you are an employer establishing workplace policies or an employee facing unfair treatment, our employment practice provides balanced, practical legal guidance aligned with Maldivian labor law.',
    icon_name: 'Users',
    cover_image_url: null,
    common_needs: ['Employment contracts', 'Wrongful termination', 'Workplace policies', 'Discrimination claims', 'Severance negotiations'],
    related_services: ['Regulatory Compliance', 'Civil Litigation'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 5,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '6',
    name: 'Property & Land Matters',
    slug: 'property-land',
    short_description: 'Expert guidance on property transactions and land disputes.',
    full_description: 'Property matters in the Maldives involve unique considerations. We assist with purchases, leases, development agreements, and dispute resolution, ensuring your property interests are secure.',
    icon_name: 'Home',
    cover_image_url: null,
    common_needs: ['Property purchases', 'Land registration', 'Lease agreements', 'Title disputes', 'Development contracts'],
    related_services: ['Construction Law', 'Civil Litigation'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 6,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '7',
    name: 'Banking & Finance',
    slug: 'banking-finance',
    short_description: 'Legal support for financial transactions and institutions.',
    full_description: 'From loan documentation to regulatory compliance, we support banks, financial institutions, and borrowers through complex financial transactions and regulatory matters.',
    icon_name: 'Landmark',
    cover_image_url: null,
    common_needs: ['Loan documentation', 'Security arrangements', 'Financial regulations', 'Banking disputes', 'Islamic finance'],
    related_services: ['Corporate Law', 'Regulatory Compliance'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: false,
    is_visible: true,
    sort_order: 7,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '8',
    name: 'Dispute Resolution & Arbitration',
    slug: 'dispute-resolution',
    short_description: 'Alternative pathways to resolve conflicts efficiently.',
    full_description: 'Not every dispute needs to go to court. We offer mediation and arbitration services that can resolve conflicts faster and more cost-effectively while maintaining confidentiality.',
    icon_name: 'MessageSquare',
    cover_image_url: null,
    common_needs: ['Commercial arbitration', 'Mediation services', 'Negotiated settlements', 'International disputes', 'Enforcement of awards'],
    related_services: ['Civil Litigation', 'Corporate Law'],
    process_steps: null,
    meta_title: null,
    meta_description: null,
    is_featured: false,
    is_visible: true,
    sort_order: 8,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  }
]

export const sectors: Sector[] = [
  {
    id: '1',
    name: 'Hospitality & Resorts',
    slug: 'hospitality-resorts',
    short_description: 'Legal partner to the Maldives\' world-renowned hospitality industry.',
    full_description: 'The hospitality sector is the cornerstone of the Maldivian economy. We provide comprehensive legal support to resorts, hotels, and tourism operators, from development agreements to employment matters and regulatory compliance.',
    icon_name: 'Building',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '2',
    name: 'Construction & Real Estate',
    slug: 'construction-real-estate',
    short_description: 'Building the legal foundation for development projects.',
    full_description: 'We support developers, contractors, and property owners through all phases of construction and real estate projects, from land acquisition to dispute resolution.',
    icon_name: 'HardHat',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '3',
    name: 'SMEs & Local Businesses',
    slug: 'smes-local-businesses',
    short_description: 'Empowering Maldivian entrepreneurs and growing businesses.',
    full_description: 'Small and medium enterprises are the backbone of the local economy. We provide practical, affordable legal support tailored to the needs of growing Maldivian businesses.',
    icon_name: 'Store',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '4',
    name: 'Financial Services',
    slug: 'financial-services',
    short_description: 'Navigating the regulated financial landscape.',
    full_description: 'From banks to insurance companies to fintech startups, we help financial services clients manage regulatory requirements while pursuing growth opportunities.',
    icon_name: 'TrendingUp',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: false,
    is_visible: true,
    sort_order: 4,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '5',
    name: 'International Clients',
    slug: 'international-clients',
    short_description: 'Your gateway to legal certainty in the Maldives.',
    full_description: 'Foreign investors and international businesses need local expertise. We bridge the gap, providing clear guidance on Maldivian law and facilitating smooth cross-border transactions.',
    icon_name: 'Globe',
    cover_image_url: null,
    meta_title: null,
    meta_description: null,
    is_featured: true,
    is_visible: true,
    sort_order: 5,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  }
]

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    profile_id: null,
    full_name: 'Abdul Salaam Arif',
    slug: 'abdul-salaam-arif',
    role_title: 'Co-Founder & Managing Partner',
    email: 'abdulsalaam@aureuslaw.mv',
    phone: null,
    bio: 'Abdul Salaam Arif is a leading figure in the Maldivian legal landscape, recognized for his extensive contributions to both the public sector and private legal practice. As Co-Founder and Managing Partner of Aureus Law Firm LLP, he leverages a multi-disciplinary background to provide clients with sophisticated legal solutions in a rapidly evolving regulatory environment.\n\nHis career is marked by high-level appointments that reflect his integrity and legal acumen. He served as Chief Ombudsperson for the Office for Transitional Justice (2021–2023), directing investigations into systemic injustices and collaborating with international partners on institutional reform. Previously, he held the position of Vice President of the Tax Appeal Tribunal for five years, overseeing complex tax disputes and contributing significantly to national tax policy and administration.\n\nWith nearly a decade of experience as External Legal Counsel for the Bank of Maldives and three years with the Maldives Finance Leasing Company, Abdul Salaam has a deep understanding of banking laws, corporate governance, and risk mitigation. He holds a Master of Comparative Laws and a Bachelor of Laws (Hons) from the International Islamic University Malaysia, and is licensed to practice before the Supreme Court of the Maldives.',
    education: [
      'Master of Comparative Laws, International Islamic University Malaysia',
      'Bachelor of Laws (Hons), International Islamic University Malaysia',
      'Diploma in Information Technology',
    ],
    admissions: ['Supreme Court of the Maldives'],
    languages: ['Dhivehi', 'English'],
    years_experience: 15,
    photo_url: 'https://hercules-cdn.com/file_oocqZQeJoPMU5bvd51Ic2pnk',
    is_partner: true,
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '2',
    profile_id: null,
    full_name: 'Hawwa Shahira',
    slug: 'hawwa-shahira',
    role_title: 'Co-Founder & Partner',
    email: 'hawwashahira@aureuslaw.mv',
    phone: null,
    bio: 'Hawwa Shahira is a Co-Founder and Partner at Aureus Law Firm LLP, where she advises clients on commercial, employment, regulatory, family, criminal, and compliance-related matters. She is a Licensed Attorney-at-Law in the Republic of Maldives and passed the inaugural Maldives Bar Examination conducted in 2023.\n\nHer work at Aureus includes drafting and reviewing commercial contracts, service agreements, policies, and legal opinions, advising businesses on labour law compliance, disciplinary matters, and regulatory obligations, and liaising with government authorities on behalf of clients.\n\nBefore co-founding the firm, she served as Senior Legal Officer at Maldives Civil Aviation Authority, advising on regulatory compliance, enforcement action, risk mitigation, contracts, MOUs, and statutory obligations. She also served as an Investigator at the Ombudsperson\'s Office for Transitional Justice and as a Court Officer at the Family Court of Maldives. She holds a Bachelor\'s Degree in Shariah and Law with Honours from The Maldives National University.',
    education: [
      'Bachelor of Shariah and Law (Hons), Maldives National University',
    ],
    admissions: ['Bar Council of the Maldives (2023)'],
    languages: ['Dhivehi', 'English'],
    years_experience: null,
    photo_url: 'https://hercules-cdn.com/file_a5SHXeBxIkQNwr8b7uCaDOik',
    is_partner: true,
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '3',
    profile_id: null,
    full_name: 'Samaahath Abdul Latheef',
    slug: 'samaahath-abdul-latheef',
    role_title: 'Legal Consultant',
    email: null,
    phone: null,
    bio: "Samaahath Abdul Latheef is a Legal Consultant at Aureus Law Firm, contributing a strong foundation in Shari'ah and Law together with practical experience in investigative work, court operations, and institutional legal processes. She earned her Master's Degree in Shari'ah and Law from Villa College and her Bachelor's Degree in Shari'ah and Law (Hons) from the Maldives National University.\n\nSamaahath previously served as an Investigator at the Ombudspersons Office for Transitional Justice, working on investigations involving statements, field inquiries, reporting, record management, institutional accountability, and referral processes. She also served as an Administrative Officer at the Family Court, gaining experience in case administration, hearing preparation, court records, and procedural coordination.\n\nShe has further worked with the National Centre for Information Technology, supporting e-government systems, user training, and administrative implementation. Across these roles, she has developed strengths in regulatory compliance, documentation, crisis management, collaboration, and stakeholder engagement.",
    education: [
      "Master's Degree in Shari'ah and Law, Villa College",
      "Bachelor's Degree in Shari'ah and Law (Hons), Maldives National University",
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: null,
    photo_url: 'https://hercules-cdn.com/file_ad30uex21BfKeT1lu5UPu6Mn',
    is_partner: false,
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '4',
    profile_id: null,
    full_name: 'Minha Abdul Muhsin',
    slug: 'minha-abdul-muhsin',
    role_title: 'Associate',
    email: null,
    phone: null,
    bio: "Minha Abdul Muhsin is an Associate at Aureus Law Firm, contributing a strong foundation in legal analysis, legislative review, court procedure, and human rights-informed legal practice. She earned her Master of Laws in International Human Rights Law from the University of Essex and her Bachelor of Shari'ah & Law from the Maldives National University.\n\nBefore joining Aureus, Minha served as Deputy Legal Officer at the Legal Affairs Office of the President's Office, working on legal opinions, legislative bill review, Presidential legal briefs, decrees, MOUs, and court-related matters. She also served as Legal Officer at the Juvenile Court, supporting judicial processes through legal commentary, registrar functions, judicial assistance, training coordination, and legal research.\n\nMinha has further strengthened her practice through specialized training in juvenile justice, legislative drafting, domestic violence awareness, counter-terrorism coordination, and international legal processes. She is also a published contributor in the field of disaster management law in SAARC countries.",
    education: [
      'Master of Laws (International Human Rights Law), University of Essex',
      "Bachelor of Shari'ah & Law, Maldives National University",
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: null,
    photo_url: 'https://hercules-cdn.com/file_J6zxiJ5Oq0ywCSzGqie5ZJd0',
    is_partner: false,
    is_featured: true,
    is_visible: true,
    sort_order: 4,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '5',
    profile_id: null,
    full_name: 'Mohamed Abdul Ghanee',
    slug: 'mohamed-abdul-ghanee',
    role_title: 'Associate',
    email: null,
    phone: null,
    bio: "Mohamed Abdul Ghanee is an Associate at Aureus Law Firm, contributing a strong background in legislative drafting, regulatory analysis, administrative law processes, and institutional legal advisory work. He earned his Bachelor of Laws from the Faculty of Shariah and Law, Maldives National University.\n\nBefore joining Aureus in January 2026, Mohamed served for over a decade at the Ministry of Health, first as Legal Officer and later as Senior Legal Officer, while also acting for extended periods as Head of the Ministry's Legal Section. In these roles, he was involved in the drafting and review of bills, regulations, amendments, agreements, and MOUs, and provided legal opinions on a wide range of institutional matters.\n\nHe has held leadership roles including Chairperson of the Sexual Harassment Investigation Committee and Chairperson of the Muraajaa Committee under the Right to Information Act. He also served in the country's COVID-19 emergency response structures within both the National Emergency Operation Centre and the Health Emergency Operation Centre legal clusters.",
    education: [
      'Bachelor of Laws, Faculty of Shariah and Law, Maldives National University',
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: 10,
    photo_url: 'https://hercules-cdn.com/file_27XHwgoTrYulUJAVcKgCtHXm',
    is_partner: false,
    is_featured: true,
    is_visible: true,
    sort_order: 5,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '6',
    profile_id: null,
    full_name: 'Ahmed Raaiz',
    slug: 'ahmed-raaiz',
    role_title: 'Legal Consultant',
    email: null,
    phone: null,
    bio: "Ahmed Raaiz is a Legal Consultant at Aureus Law Firm with a strong academic background in Shari'ah and Law and extensive professional experience in legal practice, investigations, and institutional legal affairs. He holds a Bachelor's Degree in Shari'ah and Law (Hons) from The Maldives National University.\n\nRaaiz has served in several public institutions, gaining experience in investigations, case management, and legal analysis across criminal, civil, family law, and child rights matters. He served as an Investigation Officer at the Maldives Police Service, handling criminal investigations, evidence analysis, witness interviews, and prosecution support.\n\nHe also served at the Ombudsperson's Office for Transitional Justice investigating human rights complaints, at the Children's Ombudsperson's Office handling child rights matters, and as Legal Officer at the Local Government Authority providing legal analysis on local governance and decentralization matters.",
    education: [
      "Bachelor's Degree in Shari'ah and Law (Hons), Maldives National University",
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: null,
    photo_url: 'https://hercules-cdn.com/file_V8L9XCC0an7D6wBT6XkppSwG',
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 6,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '7',
    profile_id: null,
    full_name: 'Ibrahim Rasheed',
    slug: 'ibrahim-rasheed',
    role_title: 'Tax Consultant',
    email: null,
    phone: null,
    bio: 'Ibrahim Rasheed is a Tax Consultant at Aureus Law Firm, contributing a rare blend of legal qualification, tax advisory experience, accounting expertise, and commercial insight. He holds a Master in Comparative Law (MCL) from the Islamic University of Maldives, a Master in Islamic Finance Practice from INCEIF, and a Bachelor of Sharia & Law – LLB (Hons) from the Islamic University of Maldives. He is also a Licensed Attorney of the Bar Council of the Maldives and has pursued additional professional studies through CIMA and ACCA.\n\nOver the course of his career, Ibrahim has held roles across legal, tax, accounting, and financial management functions, including service at the Tax Appeal Tribunal, Maldives Tourism Development Corporation Plc, Wataniya Telecom Maldives Pvt Ltd, and Universal Enterprises Pvt Ltd, as well as in private advisory practice.\n\nHis experience includes advising on the legality of tax matters, financial and reporting consequences, budgeting, asset oversight, internal audit, and reporting systems improvement. At Aureus Law Firm, he brings a disciplined and commercially practical perspective to tax consultancy.',
    education: [
      'Master in Comparative Law (MCL), Islamic University of Maldives',
      'Master in Islamic Finance Practice, INCEIF',
      'Bachelor of Sharia & Law – LLB (Hons), Islamic University of Maldives',
    ],
    admissions: ['Bar Council of the Maldives'],
    languages: ['Dhivehi', 'English'],
    years_experience: null,
    photo_url: 'https://hercules-cdn.com/file_iJZw69vBG2s6p4zlDADEm82R',
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 7,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '8',
    profile_id: null,
    full_name: 'Fathimath Fazuna',
    slug: 'fathimath-fazuna',
    role_title: 'Social Inclusion Consultant',
    email: null,
    phone: null,
    bio: 'Fathimath Fazuna is the Social Inclusion Consultant at Aureus Law Firm, where she contributes a strong background in human rights, mediation, social development, counselling, and inclusive community engagement. Her role focuses on advancing equality, diversity, and inclusion through internal policy support, culture-building, client service considerations, and community-facing initiatives.\n\nFazuna holds a Bachelor\'s Degree in Sociology and Anthropology from the International Islamic University of Malaysia, a Master\'s Degree in Development Studies from the University of Malaya, and a Diploma in Counselling Psychology from the American College of Higher Education, Sri Lanka.\n\nHer career spans over two decades including service as Senior Social Service Worker at the National Drug Agency, Human Rights Officer at the Human Rights Commission of the Maldives, Mediator at the Ombudspersons Office for Transitional Justice, and Gender, Nutrition and Social Inclusion Coordinator at the Maldives Agribusiness Program.',
    education: [
      "Bachelor's Degree in Sociology and Anthropology, International Islamic University of Malaysia",
      "Master's Degree in Development Studies, University of Malaya",
      'Diploma in Counselling Psychology, American College of Higher Education, Sri Lanka',
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: 20,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 8,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '9',
    profile_id: null,
    full_name: 'Aminath Mohamed',
    slug: 'aminath-mohamed',
    role_title: 'Business Management & Marketing Consultant',
    email: null,
    phone: null,
    bio: "Aminath Mohamed is the Business Management and Marketing Consultant at Aureus Law Firm, contributing experience in business operations, institutional leadership, stakeholder engagement, strategic coordination, and marketing-related organizational support. Her academic background includes a Master's in Business from the Maldives Business School, a Bachelor's in Business / Management and Marketing, and a Diploma in Business from the Maldives National University.\n\nHer professional experience spans leadership and administrative roles at the National Centre for the Arts, the Ministry of Youth Empowerment, Information and Arts, the Ombudspersons Office for Transitional Justice, the Department of Judicial Administration – Judicial Academy, STRADA Maldives, and State Trading Organisation Plc.\n\nAcross these roles, she has developed practical strengths in management support, finance and procurement administration, case and workflow coordination, reporting, communication, and institutional organization.",
    education: [
      "Master's in Business, Maldives Business School",
      "Bachelor's in Business / Management and Marketing, Maldives National University",
      'Diploma in Business, Maldives National University',
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: null,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 9,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '10',
    profile_id: null,
    full_name: 'Moosa Riffath',
    slug: 'moosa-riffath',
    role_title: 'IT Professional',
    email: null,
    phone: null,
    bio: 'Moosa Riffath is an IT professional supporting Aureus Law Firm, assisting with technology-related operations, system support, network maintenance, and general IT support. He brings practical IT experience from legal, education, public sector, and corporate environments.\n\nHis academic background includes a Bachelor of Information Technology in System Administration from Cyryx College and a Diploma in Information Technology from the same institution. He is currently pursuing an MSc in Information Technology at Villa College, Maldives, affiliated with the University of the West of England.\n\nMoosa\'s experience includes his current role as ICT Manager at Road Development Corporation, as well as previous technical roles at the Ombudsperson\'s Office for Transitional Justice, Criminal Court, and Majeediyya School. Across these roles, he has developed strengths in IT troubleshooting, network operations, server support, Microsoft administration, hardware and software support, and user-focused technical assistance.',
    education: [
      'Bachelor of Information Technology (System Administration), Cyryx College',
      'Diploma in Information Technology, Cyryx College',
      'MSc in Information Technology (in progress), Villa College / University of the West of England',
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: null,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 10,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
  {
    id: '11',
    profile_id: null,
    full_name: 'Ismail Iyaadh Shaheed',
    slug: 'ismail-iyaadh-shaheed',
    role_title: 'Junior Legal Associate',
    email: null,
    phone: null,
    bio: "Ismail Iyaadh Shaheed is a Junior Legal Associate at Aureus Law Firm LLP with more than seven years of professional experience across government, legal, and institutional settings, with work involving legal support, public administration, governance, regulatory review, legislative processes, and institutional coordination.\n\nAt Aureus, Iyaadh assists with legal research, case preparation, document review, contract and agreement review, client correspondence, and matters before courts and tribunals. Before joining the firm, he worked in several areas of the Maldivian public sector, supporting legal affairs, parliamentary and legislative processes, national security work, public administration, and policy-related matters.\n\nHis experience includes supporting legislative and regulatory procedures, ratification processes, administrative decisions, right to information procedures, and legal research. His areas of interest include public law, employment law, commercial and contractual matters, governance, regulatory compliance, human rights, and national security. He holds a Bachelor of Shari'ah and Law (Honours) from Maldives National University.",
    education: [
      "Bachelor of Shari'ah and Law (Honours), Maldives National University",
    ],
    admissions: null,
    languages: ['Dhivehi', 'English'],
    years_experience: 7,
    photo_url: null,
    is_partner: false,
    is_featured: false,
    is_visible: true,
    sort_order: 11,
    linkedin_url: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
  },
]

export const articleCategories: ArticleCategory[] = [
  { id: '1', name: 'Legal Updates', slug: 'legal-updates', description: 'Recent changes in Maldivian law and regulations', sort_order: 1, created_at: '2025-12-08' },
  { id: '2', name: 'Business Insights', slug: 'business-insights', description: 'Practical guidance for businesses operating in the Maldives', sort_order: 2, created_at: '2025-12-08' },
  { id: '3', name: 'Industry Focus', slug: 'industry-focus', description: 'Deep dives into sector-specific legal matters', sort_order: 3, created_at: '2025-12-08' },
  { id: '4', name: 'Client Guides', slug: 'client-guides', description: 'Helpful resources for common legal questions', sort_order: 4, created_at: '2025-12-08' },
  { id: '5', name: 'Firm News', slug: 'firm-news', description: 'Updates and announcements from Aureus Law', sort_order: 5, created_at: '2025-12-08' }
]

export const articles: Article[] = [
  {
    id: '1',
    title: 'Understanding Employment Law in the Maldives',
    slug: 'understanding-employment-law-maldives',
    excerpt: 'A practical guide to employment rights, obligations, and compliance for businesses and workers in the Maldives.',
    content: '<p>Maldivian employment law governs the rights and obligations of employers and employees operating in the country. Understanding these rules is essential for businesses to remain compliant and for workers to know their rights.</p><h2>Key Employer Obligations</h2><p>Employers must provide written employment contracts, ensure safe working conditions, pay wages on time, and comply with leave entitlements as prescribed under Maldivian labor regulations.</p><h2>Employee Rights</h2><p>Employees are entitled to annual leave, sick leave, and other protections. Unfair dismissal is prohibited and may lead to claims before the Employment Tribunal.</p><h2>How We Can Help</h2><p>Our employment practice provides advice on contracts, disciplinary procedures, regulatory compliance, and representation in disputes. Contact Aureus Law Firm LLP for tailored employment law support.</p>',
    cover_image_url: null,
    category_id: '1',
    author_id: '2',
    status: 'published',
    is_featured: true,
    read_time_minutes: 5,
    tags: ['employment law', 'HR', 'compliance'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2025-12-08',
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
    category: articleCategories[0],
    author: teamMembers[1]
  },
  {
    id: '2',
    title: 'Guide to Property Transactions in the Maldives',
    slug: 'property-transactions-guide-maldives',
    excerpt: 'A practical guide to property purchases, leases, and land matters in the Maldives, including due diligence requirements.',
    content: '<p>Property matters in the Maldives involve unique legal considerations. Whether you are a local buyer, a business, or a foreign investor, understanding the legal framework is essential before entering any property transaction.</p><h2>Key Considerations</h2><p>Foreign nationals and companies can access property in the Maldives primarily through long-term lease arrangements. Due diligence is critical before completing any transaction.</p><h2>Due Diligence</h2><p>Before proceeding, it is important to verify ownership, review encumbrances, and confirm all necessary permits. Our team can guide you through the entire process.</p><p>Contact Aureus Law Firm LLP for property advisory and transactional support.</p>',
    cover_image_url: null,
    category_id: '4',
    author_id: '1',
    status: 'published',
    is_featured: true,
    read_time_minutes: 7,
    tags: ['property law', 'real estate', 'due diligence'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2025-12-08',
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
    category: articleCategories[3],
    author: teamMembers[0]
  },
  {
    id: '3',
    title: 'Corporate Compliance for Maldivian Businesses',
    slug: 'corporate-compliance-maldivian-businesses',
    excerpt: 'What businesses operating in the Maldives need to know about regulatory compliance, governance, and risk management.',
    content: '<p>Good corporate compliance is the foundation of sustainable business in the Maldives. Implementing robust governance practices builds trust with investors, partners, and regulators.</p><h2>Key Compliance Areas</h2><p>Businesses must comply with company law, employment regulations, tax obligations, and sector-specific rules. Clear internal policies and sound governance reduce risk significantly.</p><h2>Risk Management</h2><p>Establishing clear compliance frameworks helps companies identify and address issues before they escalate. Our team assists with compliance reviews and implementation of best practices.</p>',
    cover_image_url: null,
    category_id: '2',
    author_id: '1',
    status: 'published',
    is_featured: false,
    read_time_minutes: 6,
    tags: ['corporate law', 'governance', 'compliance'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2025-12-08',
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
    category: articleCategories[1],
    author: teamMembers[0]
  },
  {
    id: '4',
    title: 'Tax Advisory in the Maldives: What You Need to Know',
    slug: 'tax-advisory-maldives',
    excerpt: 'An overview of tax obligations, dispute resolution, and compliance for businesses and individuals in the Maldives.',
    content: '<p>Tax law in the Maldives has evolved significantly in recent years. Whether you are a business, a financial institution, or an individual, understanding your tax obligations is essential.</p><h2>Key Tax Obligations</h2><p>Businesses must comply with GST, Business Profit Tax (BPT), and other applicable taxes. Accurate filing and timely payment are critical to avoiding penalties.</p><h2>Tax Disputes</h2><p>When disputes arise with the tax authority, the Tax Appeal Tribunal provides a forum for resolution. Our team has deep experience in tax litigation and advisory at the highest levels.</p>',
    cover_image_url: null,
    category_id: '3',
    author_id: '7',
    status: 'published',
    is_featured: false,
    read_time_minutes: 8,
    tags: ['tax law', 'compliance', 'advisory'],
    attachment_url: null,
    meta_title: null,
    meta_description: null,
    published_at: '2025-12-08',
    created_at: '2025-12-08',
    updated_at: '2025-12-08',
    category: articleCategories[2],
    author: teamMembers[6]
  }
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    client_name: 'Ibrahim Moosa',
    client_title: 'CEO',
    company_name: 'Island Resorts Group',
    content: 'Aureus Law has been our trusted legal partner. Their understanding of the Maldivian legal landscape and proactive approach to legal matters has been invaluable to our business.',
    rating: 5,
    practice_area_id: '1',
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    created_at: '2025-12-08'
  },
  {
    id: '2',
    client_name: 'Sarah Chen',
    client_title: 'Regional Director',
    company_name: 'Pacific Investments Ltd',
    content: 'When we decided to invest in the Maldives, Aureus Law provided clear, practical guidance that made the process smooth. Their team understood our commercial objectives and delivered results.',
    rating: 5,
    practice_area_id: '1',
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    created_at: '2025-12-08'
  },
  {
    id: '3',
    client_name: 'Ahmed Saleem',
    client_title: 'Managing Director',
    company_name: 'Coral Construction',
    content: 'The team at Aureus Law helped us navigate complex agreements and resolve a challenging dispute. Professional, thorough, and always available when needed.',
    rating: 5,
    practice_area_id: '6',
    is_featured: true,
    is_visible: true,
    sort_order: 3,
    created_at: '2025-12-08'
  }
]

export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'How do I schedule a consultation with Aureus Law?',
    answer: 'You can schedule a consultation by filling out our online booking form, calling our office at +960 300 1000, or sending an email to contact@aureuslaw.mv. We typically respond within one business day and will arrange a time that suits your schedule.',
    category: 'General',
    practice_area_id: null,
    sort_order: 1,
    is_visible: true,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '2',
    question: 'What are your fees and billing practices?',
    answer: 'Our fees vary depending on the nature and complexity of the matter. We offer fixed-fee arrangements for routine matters and hourly billing for more complex work. During your initial consultation, we will provide a clear estimate of costs and explain our billing practices.',
    category: 'General',
    practice_area_id: null,
    sort_order: 2,
    is_visible: true,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '3',
    question: 'Do you offer services in languages other than English and Dhivehi?',
    answer: 'Yes, our team members are fluent in both Dhivehi and English. Please let us know your language preference when scheduling your consultation.',
    category: 'General',
    practice_area_id: null,
    sort_order: 3,
    is_visible: true,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '4',
    question: 'How do I incorporate a company in the Maldives?',
    answer: 'Company incorporation involves registering with the Ministry of Economic Development, obtaining necessary licenses, and preparing constitutional documents. Our team can guide you through the entire process, from choosing the right business structure to completing registration.',
    category: 'Business',
    practice_area_id: '1',
    sort_order: 4,
    is_visible: true,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '5',
    question: 'What should I do if I receive a legal notice?',
    answer: 'Do not ignore any legal notice. Contact a lawyer promptly to understand your rights and obligations. Time limits often apply to legal responses, so early advice is essential.',
    category: 'Disputes',
    practice_area_id: '2',
    sort_order: 5,
    is_visible: true,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '6',
    question: 'How long does a typical court case take in the Maldives?',
    answer: 'Case duration varies significantly depending on the court, complexity, and nature of the dispute. Simple matters may resolve in months, while complex litigation can take several years. We can provide more specific guidance based on your circumstances.',
    category: 'Disputes',
    practice_area_id: '2',
    sort_order: 6,
    is_visible: true,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  }
]

// Portal Demo Data
export const demoClients: Client[] = [
  {
    id: '1',
    name: 'Island Resorts Group',
    client_type: 'business',
    email: 'legal@islandresorts.mv',
    phone: '+960 400 1000',
    address: 'Tower 1, Hulhumalé Business Park',
    company_name: 'Island Resorts Group Pvt Ltd',
    contact_person: 'Ibrahim Moosa',
    notes: 'Major hospitality client.',
    is_active: true,
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '2',
    name: 'Mohamed Rashid',
    client_type: 'individual',
    email: 'mrashid@gmail.com',
    phone: '+960 777 1234',
    address: 'H. Sunrise, Malé',
    company_name: null,
    contact_person: null,
    notes: 'Family law matter - divorce proceedings.',
    is_active: true,
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '3',
    name: 'Coral Construction Pvt Ltd',
    client_type: 'business',
    email: 'info@coralconstruction.mv',
    phone: '+960 400 2000',
    address: 'Industrial Zone, Thilafushi',
    company_name: 'Coral Construction Pvt Ltd',
    contact_person: 'Ahmed Saleem',
    notes: 'Construction and development client.',
    is_active: true,
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  }
]

export const demoCases: Case[] = [
  {
    id: '1',
    case_number: 'AL-2025-00001',
    title: 'Island Resorts Group - Employment Dispute',
    description: 'Wrongful termination claim by former employee. Client is defendant.',
    client_id: '1',
    practice_area_id: '5',
    status: 'active',
    priority: 'high',
    court_name: 'Employment Tribunal',
    court_case_number: 'ET-2025-0123',
    next_hearing_date: '2025-03-15T10:00:00Z',
    deadline: '2025-03-10T17:00:00Z',
    notes: 'Key witness interview scheduled for next week.',
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '2',
    case_number: 'AL-2025-00002',
    title: 'Rashid Divorce Proceedings',
    description: 'Contested divorce with child custody dispute.',
    client_id: '2',
    practice_area_id: '4',
    status: 'active',
    priority: 'medium',
    court_name: 'Family Court',
    court_case_number: 'FC-2025-0456',
    next_hearing_date: '2025-03-20T09:00:00Z',
    deadline: null,
    notes: 'Mediation attempt scheduled before hearing.',
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '3',
    case_number: 'AL-2025-00003',
    title: 'Coral Construction - Contract Review',
    description: 'Review and negotiation of major development contract for new resort project.',
    client_id: '3',
    practice_area_id: '1',
    status: 'active',
    priority: 'high',
    court_name: null,
    court_case_number: null,
    next_hearing_date: null,
    deadline: '2025-02-28T17:00:00Z',
    notes: 'Client meeting next week to discuss revised terms.',
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
]

export const demoTasks: Task[] = [
  {
    id: '1',
    title: 'Prepare witness statements',
    description: 'Draft witness statements for employment tribunal hearing.',
    case_id: '1',
    assigned_to: null,
    assigned_by: null,
    priority: 'high',
    status: 'in_progress',
    due_date: '2025-03-08T17:00:00Z',
    completed_at: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '2',
    title: 'Review contract draft',
    description: 'Review latest draft of development contract and prepare markup.',
    case_id: '3',
    assigned_to: null,
    assigned_by: null,
    priority: 'high',
    status: 'pending',
    due_date: '2025-02-25T17:00:00Z',
    completed_at: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '3',
    title: 'File mediation request',
    description: 'Submit mediation request to Family Court for Rashid matter.',
    case_id: '2',
    assigned_to: null,
    assigned_by: null,
    priority: 'medium',
    status: 'completed',
    due_date: '2025-01-15T17:00:00Z',
    completed_at: '2025-01-14T14:30:00Z',
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
]

export const demoAppointments: Appointment[] = [
  {
    id: '1',
    title: 'Island Resorts Group - Case Strategy Meeting',
    description: 'Discuss strategy for upcoming tribunal hearing.',
    client_id: '1',
    case_id: '1',
    consultation_request_id: null,
    assigned_to: null,
    location: 'Aureus Law Firm Office',
    start_time: '2025-02-20T10:00:00Z',
    end_time: '2025-02-20T11:30:00Z',
    status: 'confirmed',
    notes: 'Ibrahim Moosa and HR Director attending.',
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
  {
    id: '2',
    title: 'Coral Construction - Contract Negotiation',
    description: 'Review revised contract terms with client.',
    client_id: '3',
    case_id: '3',
    consultation_request_id: null,
    assigned_to: null,
    location: 'Client Office',
    start_time: '2025-02-25T14:00:00Z',
    end_time: '2025-02-25T16:00:00Z',
    status: 'pending',
    notes: 'Bring printed copies of contract comparison.',
    created_by: null,
    created_at: '2025-12-08',
    updated_at: '2025-12-08'
  },
]

export const demoNotifications: Notification[] = [
  {
    id: '1',
    profile_id: '',
    title: 'New task assigned',
    message: 'You have been assigned to review contract draft for Coral Construction.',
    type: 'task',
    link: '/portal/tasks',
    is_read: false,
    created_at: '2025-12-15T09:00:00Z'
  },
  {
    id: '2',
    profile_id: '',
    title: 'Hearing reminder',
    message: 'Employment Tribunal hearing for Island Resorts Group in 3 days.',
    type: 'reminder',
    link: '/portal/cases/1',
    is_read: false,
    created_at: '2025-12-12T08:00:00Z'
  },
  {
    id: '3',
    profile_id: '',
    title: 'Document uploaded',
    message: 'New document uploaded to Rashid Divorce Proceedings case.',
    type: 'document',
    link: '/portal/cases/2',
    is_read: true,
    created_at: '2025-12-10T14:30:00Z'
  }
]

export const demoConsultationRequests: ConsultationRequest[] = [
  {
    id: '1',
    full_name: 'Ali Hassan',
    email: 'ali.hassan@example.com',
    phone: '+960 777 5555',
    client_type: 'individual',
    company_name: null,
    practice_area_id: '4',
    preferred_date: '2025-03-25',
    preferred_time: 'morning',
    message: 'I need advice regarding a family matter involving child custody.',
    status: 'new',
    internal_notes: null,
    assigned_to: null,
    created_at: '2025-12-18T10:00:00Z',
    updated_at: '2025-12-18T10:00:00Z'
  },
  {
    id: '2',
    full_name: 'Fatima Ahmed',
    email: 'fatima@oceanventures.mv',
    phone: '+960 400 8888',
    client_type: 'business',
    company_name: 'Ocean Ventures Pvt Ltd',
    practice_area_id: '1',
    preferred_date: '2025-03-27',
    preferred_time: 'afternoon',
    message: 'Looking for legal support for a new joint venture agreement.',
    status: 'reviewed',
    internal_notes: 'Potential high-value client. To follow up.',
    assigned_to: null,
    created_at: '2025-12-16T14:00:00Z',
    updated_at: '2025-12-17T09:00:00Z'
  }
]

// Job Openings
export const jobOpenings = [
  {
    id: '1',
    title: 'Associate Attorney – Litigation',
    type: 'Full-time',
    location: 'Malé, Maldives',
    description: 'We are seeking a motivated Associate Attorney to join our Litigation & Dispute Resolution practice. The ideal candidate will assist in court proceedings, legal research, case preparation, and client advisory.',
    requirements: [
      'Bachelor of Laws or Bachelor of Shariah & Law from a recognized university',
      '1-3 years of relevant experience',
      'Strong research and drafting skills',
      'Fluency in English and Dhivehi',
      'Admission or eligibility for admission to the Bar Council of Maldives'
    ],
    posted_date: '2025-12-08',
  },
  {
    id: '2',
    title: 'Legal Associate – Corporate & Regulatory',
    type: 'Full-time',
    location: 'Malé, Maldives',
    description: 'Join our Corporate, Regulatory & Advisory team to support clients with business formation, contracts, compliance, and regulatory matters.',
    requirements: [
      'Bachelor of Laws or Bachelor of Shariah & Law from a recognized university',
      'Strong drafting and advisory skills',
      'Fluency in English and Dhivehi',
      'Attention to detail and client focus'
    ],
    posted_date: '2025-12-08',
  },
  {
    id: '3',
    title: 'Paralegal / Legal Support Officer',
    type: 'Full-time',
    location: 'Malé, Maldives',
    description: 'Support our legal team with document preparation, research, court filings, and administrative tasks. An excellent opportunity for those looking to build a career in law.',
    requirements: [
      'Degree in Law or related field',
      'Strong organizational skills',
      'Proficiency in Microsoft Office',
      'Fluency in English and Dhivehi',
      'Attention to detail'
    ],
    posted_date: '2025-12-08',
  }
]

// Alias exports for portal compatibility
export const matters = demoCases.map((c, idx) => ({
  ...c,
  title: c.title,
  matter_number: c.case_number,
  assigned_lawyers: idx < 2 ? ['lawyer-1', 'lawyer-2'] : ['lawyer-1'],
  lead_lawyer_id: 'lawyer-1',
  priority: c.priority || 'medium',
}))

export const clients = demoClients

export const timeEntries = [
  {
    id: 'te-1',
    lawyer_id: 'lawyer-1',
    matter_id: 'case-1',
    date: '2025-12-18',
    hours: 2.5,
    description: 'Contract review and markup',
    billable: true,
    rate: 350,
  },
  {
    id: 'te-2',
    lawyer_id: 'lawyer-1',
    matter_id: 'case-2',
    date: '2025-12-18',
    hours: 1.5,
    description: 'Client meeting - due diligence discussion',
    billable: true,
    rate: 350,
  },
  {
    id: 'te-3',
    lawyer_id: 'lawyer-1',
    matter_id: 'case-3',
    date: '2025-12-18',
    hours: 3.0,
    description: 'Court filing preparation',
    billable: true,
    rate: 350,
  },
]
